### ISSUE TITLE
Import large JavaScript libraries (JQuery)

### ISSUE THREAD

**Issue by tanhakabir** [MicrosoftEdge/wptest#19] opened 2018-07-03 21:15 UTC
- Difficult because we export these tests and libraries are too large 
- Makes tests no longer isolated

**Comment by FremyCompany** [comment] 2018-11-06 23:31
Closed as rejected by design; I feel like authors that need big libraries shouldn't be using this site

**Closed by FremyCompany** 2018-11-06 23:31 UTC
Labels: low priority
